Added the preprocessor macro _CRT_SECURE_NO_WARNINGS to shg and testing to prevent compiler error C4996 which forbids using strcpy() and others. Added source files to testing. Added additional include directory to testing to include shg header files. Compilation stops because of compiler error C2026 - the string was longer than the limit of 16380 single-byte characters in drbnwts3.cc.